In [3]:
import numpy as np
A = np.array([[1,1,1],
             [1,2,2],
              [1,2,3]])

# Doolittle's LU decomposition
 In Doolittle's LU decomposition, we take the diagonals of the lower triangular matrix as 1 and the upper triangular matrix is initialised as full of zeros.

In [4]:
def dlu(A):
    n = len(A)
    L = np.eye(n)
    U = np.zeros((n,n))
    for i in range(n):
        for j in range(n):
            if (i>j):
                L[i,j] = A[i,j]
                for k in range(j):
                    L[i,j] -= L[i,k]*U[k,j]
                L[i,j] /= U[j,j]
            elif (j>=i):
                U[i,j] = A[i,j]
                for k in range(i):
                    U[i,j] -= L[i,k]*U[k,j]
                U[i,j] /= L[i,i]

    return L,U

In [5]:
l,u = dlu(A)
l,u

(array([[1., 0., 0.],
        [1., 1., 0.],
        [1., 1., 1.]]),
 array([[1., 1., 1.],
        [0., 1., 1.],
        [0., 0., 1.]]))

In [6]:
A

array([[1, 1, 1],
       [1, 2, 2],
       [1, 2, 3]])

In [7]:
l@u

array([[1., 1., 1.],
       [1., 2., 2.],
       [1., 2., 3.]])

# Crout's LU decomposition
 In Crout's LU decomposition, we take the diagonals of the upper triangular matrix as 1 and the lower triangular matrix is initialised as full of zeros.

In [8]:
def clu(A):
    n = len(A)
    L = np.zeros((n,n))
    U = np.eye(n)
    for i in range(n):
        for j in range(n):
            if (i>=j):
                L[i,j] = A[i,j]
                for k in range(j):
                    L[i,j] -= L[i,k]*U[k,j]
                L[i,j] /= U[j,j]
            elif (j>i):
                U[i,j] = A[i,j]
                for k in range(i):
                    U[i,j] -= L[i,k]*U[k,j]
                U[i,j] /= L[i,i]

    return L,U

In [9]:
l,u = clu(A)

In [10]:
l@u

array([[1., 1., 1.],
       [1., 2., 2.],
       [1., 2., 3.]])

# Cholesky's LU decomposition

The upper triangular matrix is the transpose of the lower triangular matrix i.e. $A=L \cdot L^{T}$

In [13]:
def chlu(A):
    n = len(A)
    L = np.zeros((n,n))
    U = np.zeros((n,n))
    for i in range(n):
        for j in range(n):
            if (i==j):
                L[i,j] = A[i,j]
                for k in range(j):
                    L[i,j] -= L[i,k]**2
                L[i,j] = L[i,j]**(0.5)
            elif (i>j):
                L[i,j] = A[j,i]
                for k in range(j):
                    L[i,j] -= L[j,k]*L[i,k]
                L[i,j] /= L[j,j]
    U = L.transpose()
    return L,U

In [15]:
l,u = chlu(A)
l@u

array([[1., 1., 1.],
       [1., 2., 2.],
       [1., 2., 3.]])